# Frontend Dockerfile (./frontend/Dockerfile)

# Use Nginx to serve the static HTML page
FROM nginx:alpine
# Copy the static HTML files into the Nginx server
COPY . /usr/share/nginx/html
# Nginx will automatically start and serve the files
