version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  e2e:
    image: cypress/included:4.12.1
    depends_on:
      - backend
      - frontend
    volumes:
      - ./e2e:/e2e
    working_dir: /e2e
    command: "cypress run"
